version: "3.6"

services:
  splunk:
    image: "splunk/splunk:latest"
    container_name: op_events_reporting
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
      - SPLUNK_PASSWORD=hey1234567890
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    volumes:
      - ${PWD}/op_events_reporting:/opt/splunk/etc/apps/op_events_reporting
      - ${PWD}/splunkd.log:/opt/splunk/var/log/splunk/splunkd.log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 20
